apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: "semver:*"
spec:
  releaseName: dev
  chart:
    git: git@github.com:okteto/flux-getting-started
    path: chart
    ref: master
  values:
    replicaCount: 2
    image:
      repository: okteto/hello-world
      tag: golang
